### ISSUE TITLE
Install pyhsmm で urllib.error.HTTPError: HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by kishiyamat** [RyoOzaki/npbdaa#3]
Eigen のリポジトリは bitbucket から gitlab に移行したようです。(参照: https://github.com/spack/spack/issues/13890)
したがって https://github.com/RyoOzaki/pyhsmm の `setup.py` も deprecate しています。Eigenのダウンロードのスクリプトをフォーク元と同様、以下のように変更すればエラーは解消します。加えて、import に requests を追加する必要もあります。

```python
# download Eigen if we don't have it in deps
eigenurl = 'https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz'
eigentarpath = os.path.join('deps', 'Eigen.tar.gz')
eigenpath = os.path.join('deps', 'Eigen')
if not os.path.exists(eigenpath):
    print('Downloading Eigen...')
    r = requests.get(eigenurl)
    with open(eigentarpath, 'wb') as f:
        f.write(r.content)
    with tarfile.open(eigentarpath, 'r') as tar:
        tar.extractall('deps')
    thedir = glob(os.path.join('deps', 'eigen-*'))[0]
    shutil.move(os.path.join(thedir, 'Eigen'), eigenpath)
    print('...done!')
```

ですが、もしソース元でフォークのモチベーションである "But, the master repository's codes include some bugs in cython codes." が解消されているならば、 mattjj/pyhsmm を利用させるか、"some bugs in cython codes" のプルリクエストを mattjj/pyhsmm に送った方が、今後のメンテナンスコストが下がるように思えます。

先日は Issue の解決ありがとうございました。RyoOzaki/pyhsmm の issue 機能が有効化されていない、また RyoOzaki/npbdaa のセットアップ 中のエラーであるためこちらに失礼します。

**Comment by kishiyamat** [comment]
npbdaa の setup.py でも同様のエラーになるようです。

**Comment by RyoOzaki** [comment]
修正しました．
ご報告ありがとうございました．
